### ISSUE TITLE
different sensor F23 not working

### ISSUE THREAD

**Issue by ehspill** [VGerris/Anyka_ak3918_hacking_journey#1]
is there any way to get a different sensor working with the rtsp?

[root@anyka /mnt/Factory]$ /mnt/Factory/custom/rtsp
default log level=4
[ak_vi_match_sensor:849] config_file: /etc/jffs2/

[check_data:212] config file: /etc/jffs2/isp_f23_mipi2lane.conf is old version
[check_file:338] read sensor fail

[ak_rtsp_vi_init:150] match sensor failed

vi init fail

my sensor 
/usr/modules/sensor_f23_mipi.ko
/etc/jffs2/sensor_gc1054.conf

**Comment by VGerris** [comment]
hi,

Based on your post, it is not clear to me what precisely the problem is.
You can use any sensor, I think the one used is in one of the startup files.

I haven't added all my changes here that I made for my cam, I had to move the ko file around and modify scripts to unpack. If you just start from the startup scripts and follow the thread, it should be clear.
For example my cam had the ko file compressed and unpacked it to temp, so I used synlinks to make things work.

In general your ko file needs to be for the same kernel version AFAIK.
And you probably need a same named config file to match, not gc1054.

I am writing this from memory, it has been a while since I worked on it. My cams just work all open source based now, I removed the cloud things and overwrote the image.

The most important is to set the name for your sensor as it is now for the default one and check if the ko file exists ( like go to / and do find . -name *.ko ).
If it is missing you need the proper version in the proper place.

I hope that helps, please give some feedback if you took a good crack at it !
